import SwiftUI
import SwiftData
import PacerCore
import PacerUI

/// Project-alias management, presented as a sheet from the Projects tab.
///
/// Replaces the old Settings → Data → "Project aliases" card. It used to
/// list every `ProjectPathAlias` in one flat column, which on a real
/// install meant 20–40 rows — overwhelmingly auto-generated git-root
/// rollups and sibling-worktree merges — burying the handful the user
/// actually created by hand. This view splits them:
///
///   • **Manual** aliases (renames, cross-machine restores, accepted
///     git-remote suggestions) are shown up top, always expanded — these
///     are the rows a user reasons about.
///   • **Auto-detected** aliases (`isAutoGenerated == true`, written
///     silently by `ProjectGitRootAutoAliaser`) collapse behind a
///     disclosure, so the machine's bookkeeping stays available for
///     audit/undo without cluttering the surface.
///
/// Lives in the Projects tab rather than Settings because that's where
/// the *create* side of the workflow already is — every project row has
/// "Merge into…" / "Merge others into this…" context menus. This
/// completes the loop: view, edit, and delete existing aliases next to
/// where you make them.
///
/// Each write still flows through `ProjectPathAliasManager.upsert/remove`
/// (cycle + self-alias validation) and the next `ScanCoordinator` cycle
/// re-attributes existing samples on the alias-fingerprint drift — no
/// plumbing here beyond writing the row.
struct ProjectAliasManager: View {
    @Environment(\.dismiss) private var dismiss
    @Environment(\.modelContext) private var modelContext

    @Query(sort: [SortDescriptor(\ProjectPathAlias.createdAt, order: .reverse)])
    private var aliases: [ProjectPathAlias]
    /// All known project paths (from `ProjectDailyAggregate`) — used as
    /// the canonical/source picker source AND as input to the git-origin
    /// auto-suggest pass.
    @Query private var projectAggregates: [ProjectDailyAggregate]

    @State private var showingEditor: AliasDraft?
    @State private var bulkMergeDraft: BulkMergeDraft?
    @State private var lastError: String?
    /// Git-remote suggestions — paths that share the same git remote
    /// origin url but live at different on-disk locations. Opt-in (the
    /// git-root sub-path rollup is silent + automatic in the scanner).
    @State private var suggestions: [ProjectGitOriginScanner.Suggestion] = []
    @State private var suggestionsLoaded = false
    @State private var dismissedSuggestionKeys: Set<String> = []
    /// Auto-detected rows start collapsed — the whole point of the split
    /// is that you rarely need to look at them.
    @State private var autoExpanded = false

    private var manualAliases: [ProjectPathAlias] {
        aliases.filter { !$0.isAutoGenerated }
    }
    private var autoAliases: [ProjectPathAlias] {
        aliases.filter { $0.isAutoGenerated }
    }

    /// All project paths Pacer has seen, deduplicated. Drives both the
    /// editor's picker and the git-origin auto-suggest pass.
    private var knownProjectPaths: [String] {
        var set: Set<String> = []
        for agg in projectAggregates {
            if agg.projectPath != ProjectDailyAggregate.unknownProjectPath {
                set.insert(agg.projectPath)
            }
        }
        return set.sorted()
    }

    var body: some View {
        VStack(alignment: .leading, spacing: 0) {
            header
            Divider().opacity(0.4)
            ScrollView {
                content
                    .padding(20)
            }
        }
        .frame(width: 640, height: 600)
        .sheet(item: $showingEditor) { draft in
            AliasEditorSheet(
                draft: draft,
                knownPaths: knownProjectPaths,
                onSave: { source, canonical in save(source: source, canonical: canonical, replacing: draft.replacing) }
            )
        }
        .sheet(item: $bulkMergeDraft) { draft in
            BulkMergeSheet(
                knownPaths: knownProjectPaths,
                initialCanonical: draft.canonical.isEmpty ? nil : draft.canonical,
                initialSources: draft.sources
            )
        }
        .task(id: knownProjectPaths) {
            await reloadSuggestions()
        }
    }

    // MARK: - Header

    private var header: some View {
        HStack(alignment: .firstTextBaseline) {
            VStack(alignment: .leading, spacing: 2) {
                Text("Project aliases")
                    .font(.title2)
                    .fontWeight(.semibold)
                Text("Fold a renamed folder, sibling worktree, or restored backup into its current project.")
                    .font(.callout)
                    .foregroundStyle(.secondary)
            }
            Spacer()
            Button("Done") { dismiss() }
                .keyboardShortcut(.defaultAction)
        }
        .padding(20)
    }

    // MARK: - Content

    @ViewBuilder
    private var content: some View {
        VStack(alignment: .leading, spacing: 16) {
            actionButtons

            if aliases.isEmpty && suggestionsVisible.isEmpty {
                emptyState
            } else {
                manualSection
                if !autoAliases.isEmpty {
                    autoSection
                }
                if !suggestionsVisible.isEmpty {
                    Divider().opacity(0.4)
                    suggestionList
                }
            }

            if let lastError {
                Text(lastError)
                    .font(.caption)
                    .foregroundStyle(.red)
            }

            footer
        }
    }

    private var actionButtons: some View {
        HStack(spacing: 8) {
            Spacer()
            if knownProjectPaths.count >= 2 {
                Button {
                    bulkMergeDraft = BulkMergeDraft(canonical: "", sources: [])
                } label: {
                    Label("Merge multiple…", systemImage: "arrow.triangle.merge")
                        .labelStyle(.titleAndIcon)
                }
                .controlSize(.small)
                .help("Pick one canonical, check every path that should fold into it. Creates all aliases at once.")
            }
            Button {
                showingEditor = AliasDraft(mode: .new, sourcePath: "", canonicalPath: "")
            } label: {
                Label("Add alias", systemImage: "plus.circle.fill")
                    .labelStyle(.titleAndIcon)
            }
            .controlSize(.small)
        }
    }

    private var emptyState: some View {
        Text("No aliases yet. Add one to merge a renamed or moved project into its current path — or right-click a project in the table and choose “Merge into…”.")
            .font(.caption)
            .foregroundStyle(.tertiary)
            .padding(.vertical, 4)
    }

    // MARK: - Manual section

    private var manualSection: some View {
        VStack(alignment: .leading, spacing: 6) {
            Eyebrow(text: "Manual")
            if manualAliases.isEmpty {
                Text("No hand-made aliases. Everything below was detected automatically.")
                    .font(.caption)
                    .foregroundStyle(.tertiary)
                    .padding(.vertical, 2)
            } else {
                ForEach(manualAliases) { alias in
                    aliasRow(for: alias)
                }
            }
        }
    }

    // MARK: - Auto-detected section

    private var autoSection: some View {
        DisclosureGroup(isExpanded: $autoExpanded) {
            VStack(alignment: .leading, spacing: 6) {
                Text("Pacer wrote these for you: subfolders of a repo fold into the repo root, and sibling git worktrees fold into the main checkout. Delete one to keep that path separate — the deletion sticks across launches.")
                    .font(.caption)
                    .foregroundStyle(.secondary)
                    .padding(.top, 4)
                ForEach(autoAliases) { alias in
                    aliasRow(for: alias)
                }
            }
            .padding(.top, 2)
        } label: {
            HStack(spacing: 6) {
                Text("Auto-detected")
                    .font(.system(size: 12, weight: .semibold))
                    .tracking(0.6)
                    .foregroundStyle(.secondary)
                Text("\(autoAliases.count)")
                    .font(.caption2)
                    .foregroundStyle(.secondary)
                    .padding(.horizontal, 6)
                    .padding(.vertical, 1)
                    .background(Capsule().fill(Color.secondary.opacity(0.15)))
            }
        }
        .padding(.top, 4)
    }

    private func aliasRow(for alias: ProjectPathAlias) -> some View {
        AliasRow(
            sourcePath: alias.sourcePath,
            canonicalPath: alias.canonicalPath,
            onEdit: {
                showingEditor = AliasDraft(
                    mode: .edit,
                    sourcePath: alias.sourcePath,
                    canonicalPath: alias.canonicalPath,
                    replacing: alias.sourcePath
                )
            },
            onDelete: { delete(alias) }
        )
    }

    // MARK: - Auto-suggest

    private var suggestionsVisible: [ProjectGitOriginScanner.Suggestion] {
        suggestions.filter { !dismissedSuggestionKeys.contains($0.id) }
    }

    private var suggestionList: some View {
        VStack(alignment: .leading, spacing: 6) {
            Eyebrow(text: "Suggested by git remote")
            ForEach(suggestionsVisible) { suggestion in
                SuggestionRow(
                    suggestion: suggestion,
                    onAccept: {
                        save(
                            source: suggestion.suggestedSource,
                            canonical: suggestion.suggestedCanonical,
                            replacing: nil
                        )
                        dismissedSuggestionKeys.insert(suggestion.id)
                    },
                    onDismiss: { dismissedSuggestionKeys.insert(suggestion.id) }
                )
            }
        }
    }

    private var footer: some View {
        Text("Pacer re-scans existing data on the next collection cycle (within seconds), so merged projects update on their own.")
            .font(.caption)
            .foregroundStyle(.tertiary)
            .padding(.top, 4)
    }

    private func reloadSuggestions() async {
        if suggestionsLoaded { return }
        let aliasedSources = Set(aliases.map(\.sourcePath))
        let result = await ProjectGitOriginScanner.suggest(
            projectPaths: knownProjectPaths,
            existingAliasedSources: aliasedSources
        )
        await MainActor.run {
            self.suggestions = result
            self.suggestionsLoaded = true
        }
    }

    // MARK: - Mutation

    private func save(source: String, canonical: String, replacing: String?) {
        let manager = ProjectPathAliasManager(context: modelContext)
        do {
            if let replacing, replacing != source {
                try manager.remove(sourcePath: replacing)
            }
            try manager.upsert(sourcePath: source, canonicalPath: canonical)
            lastError = nil
            showingEditor = nil
            NotificationCenter.default.post(name: .pacerRequestImmediateScan, object: nil)
        } catch let error as ProjectPathAliasManager.AliasError {
            lastError = error.userMessage
        } catch {
            lastError = error.localizedDescription
        }
    }

    private func delete(_ alias: ProjectPathAlias) {
        let manager = ProjectPathAliasManager(context: modelContext)
        do {
            // For an auto-detected alias, also flag the probe so the
            // scanner won't re-create it on the next cycle (esp. sibling
            // worktrees, which the sibling-merge pass would otherwise
            // re-merge immediately). Re-adding by hand brings it back as
            // a manual alias.
            try manager.remove(
                sourcePath: alias.sourcePath,
                rejectAutoMerge: alias.isAutoGenerated
            )
            lastError = nil
            NotificationCenter.default.post(name: .pacerRequestImmediateScan, object: nil)
        } catch {
            lastError = error.localizedDescription
        }
    }
}

// MARK: - Row

private struct AliasRow: View {
    let sourcePath: String
    let canonicalPath: String
    let onEdit: () -> Void
    let onDelete: () -> Void
    @State private var hovering = false

    var body: some View {
        HStack(spacing: 10) {
            VStack(alignment: .leading, spacing: 2) {
                HStack(spacing: 4) {
                    Text(pacerShortPath(sourcePath))
                        .font(.callout)
                    Image(systemName: "arrow.right")
                        .font(.system(size: 10))
                        .foregroundStyle(.tertiary)
                    Text(pacerShortPath(canonicalPath))
                        .font(.callout)
                }
                Text("\(sourcePath) → \(canonicalPath)")
                    .font(.system(.caption2, design: .monospaced))
                    .foregroundStyle(.secondary)
                    .lineLimit(1)
                    .truncationMode(.middle)
            }
            Spacer()
            Button("Edit", action: onEdit)
                .controlSize(.small)
                .opacity(hovering ? 1.0 : 0.0)
            Button(role: .destructive, action: onDelete) {
                Image(systemName: "minus.circle.fill")
                    .foregroundStyle(.secondary)
            }
            .buttonStyle(.borderless)
            .help("Remove alias")
        }
        .padding(.vertical, 4)
        .padding(.horizontal, 8)
        .background(
            RoundedRectangle(cornerRadius: 6, style: .continuous)
                .fill(hovering ? Color.primary.opacity(0.05) : Color.clear)
        )
        .onHover { hovering = $0 }
    }
}

private struct SuggestionRow: View {
    let suggestion: ProjectGitOriginScanner.Suggestion
    let onAccept: () -> Void
    let onDismiss: () -> Void

    var body: some View {
        HStack(spacing: 10) {
            VStack(alignment: .leading, spacing: 2) {
                HStack(spacing: 4) {
                    Text(pacerShortPath(suggestion.suggestedSource))
                        .font(.callout)
                    Image(systemName: "arrow.right")
                        .font(.system(size: 10))
                        .foregroundStyle(.tertiary)
                    Text(pacerShortPath(suggestion.suggestedCanonical))
                        .font(.callout)
                }
                Text("Both have remote: \(suggestion.originURL)")
                    .font(.caption)
                    .foregroundStyle(.secondary)
                    .lineLimit(1)
                    .truncationMode(.middle)
            }
            Spacer()
            Button("Merge", action: onAccept)
                .controlSize(.small)
            Button(action: onDismiss) {
                Image(systemName: "xmark.circle.fill")
                    .foregroundStyle(.tertiary)
            }
            .buttonStyle(.borderless)
            .help("Dismiss this suggestion (won't reappear until the app restarts)")
        }
        .padding(.vertical, 4)
        .padding(.horizontal, 8)
    }
}

// MARK: - Editor sheet

/// Sheet for adding or editing an alias. Two text fields with optional
/// "pick from known projects" menus, plus a Save/Cancel pair.
struct AliasDraft: Identifiable {
    enum Mode { case new, edit, merge }
    let id = UUID()
    let mode: Mode
    var sourcePath: String
    var canonicalPath: String
    /// When non-nil, this row is replacing an existing alias whose
    /// `sourcePath` may or may not match the new value. Used by
    /// `ProjectAliasManager.save` to remove the old row in edit-mode.
    var replacing: String?

    init(mode: Mode, sourcePath: String, canonicalPath: String, replacing: String? = nil) {
        self.mode = mode
        self.sourcePath = sourcePath
        self.canonicalPath = canonicalPath
        self.replacing = replacing
    }
}

struct AliasEditorSheet: View {
    let draft: AliasDraft
    let knownPaths: [String]
    let onSave: (_ source: String, _ canonical: String) -> Void
    @Environment(\.dismiss) private var dismiss

    @State private var sourcePath: String = ""
    @State private var canonicalPath: String = ""

    private var title: String {
        switch draft.mode {
        case .new:   return "Add project alias"
        case .edit:  return "Edit project alias"
        case .merge: return "Merge project into"
        }
    }

    private var isValid: Bool {
        let s = sourcePath.trimmingCharacters(in: .whitespacesAndNewlines)
        let c = canonicalPath.trimmingCharacters(in: .whitespacesAndNewlines)
        return !s.isEmpty && !c.isEmpty && s != c
    }

    var body: some View {
        VStack(alignment: .leading, spacing: 16) {
            Text(title)
                .font(.headline)
            VStack(alignment: .leading, spacing: 6) {
                Text("Source path (existing samples attribute here)")
                    .font(.caption)
                    .foregroundStyle(.secondary)
                HStack {
                    TextField("/Users/you/Code/old-name", text: $sourcePath)
                        .textFieldStyle(.roundedBorder)
                    if draft.mode != .merge {
                        Menu {
                            ForEach(knownPaths, id: \.self) { path in
                                Button(pacerShortPath(path)) { sourcePath = path }
                            }
                        } label: {
                            Image(systemName: "list.bullet")
                        }
                        .menuStyle(.borderlessButton)
                        .frame(width: 24)
                        .help("Pick from known projects")
                    }
                }
            }
            VStack(alignment: .leading, spacing: 6) {
                Text("Canonical path (samples will move here)")
                    .font(.caption)
                    .foregroundStyle(.secondary)
                HStack {
                    TextField("/Users/you/Code/new-name", text: $canonicalPath)
                        .textFieldStyle(.roundedBorder)
                    Menu {
                        ForEach(knownPaths, id: \.self) { path in
                            Button(pacerShortPath(path)) { canonicalPath = path }
                        }
                    } label: {
                        Image(systemName: "list.bullet")
                    }
                    .menuStyle(.borderlessButton)
                    .frame(width: 24)
                    .help("Pick from known projects")
                }
            }
            HStack {
                Spacer()
                Button("Cancel", role: .cancel) { dismiss() }
                Button("Save") {
                    onSave(
                        sourcePath.trimmingCharacters(in: .whitespacesAndNewlines),
                        canonicalPath.trimmingCharacters(in: .whitespacesAndNewlines)
                    )
                }
                .keyboardShortcut(.defaultAction)
                .disabled(!isValid)
            }
        }
        .padding(20)
        .frame(width: 540)
        .onAppear {
            sourcePath = draft.sourcePath
            canonicalPath = draft.canonicalPath
        }
    }
}

// MARK: - User-facing error messages

private extension ProjectPathAliasManager.AliasError {
    var userMessage: String {
        switch self {
        case .selfAlias:
            return "Source and canonical paths must be different."
        case .emptyPath:
            return "Both paths are required."
        case .wouldCreateCycle:
            return "That mapping would create a loop with an existing alias."
        }
    }
}
